### PR TITLE
Allow github actions to deploy to github artifacts registry

### PR DESCRIPTION
**Pull request by AxelRICHARD**

### CODE REVIEW

**Comment by netomi** [comment]
The organization defines read permissions for tokens by default. You can assign specific permissions in your workflow for specific jobs, see:

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

That is the preferred way to do it instead of enabling write permissions by default which would also have to be enabled on organization level first.

**Comment by netomi** [comment]
In the long run we would like to enforce read permissions by default for every Eclipse project. Here you can see some example how you define that job level permissions:

https://github.com/eclipse-sprotty/sprotty-website/blob/main/.github/workflows/preview.yml

**Comment by AxelRICHARD** [comment]
Thank you, but I would like this way to be consistent with our other repositories like eclipse-sirius.

**Comment by AxelRICHARD** [comment]
Ok I will update my workflows, thank you.

**Pull request closed without merging**
